(in-package :davenblog)

(defun submit-post ()
  (let ((time (get-universal-time))
	(title (parameter "title"))
	(body (parameter "body"))
	(tags (parameter "tags"))
	(author (parameter "author"))
	(publish (parameter "publish")))
    (when (and (valid-field-p title) (valid-field-p body))
      (let ((post (list time author title body (split-tags tags))))
	(if (valid-field-p publish)
	    (progn 
	      (post-blog-entry post)
	      (redirect "/view_entries"))
	    (preview-blog-entry post))))))

(defun submit-comment ()
  (let ((time (get-universal-time))
	(author (parameter "author"))
	(body (parameter "body"))
	(post (parameter "post")))
    (when (and (valid-field-p author) (valid-field-p body))
      (post-comment (list time author body post))
      (redirect (concatenate 'string "/view_entry?id=" post)))))